# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 561)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("duck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QGroupBox {font: oblique 12pt \"Monospace\";}\n"
"QLabel {qproperty-alignment: AlignCenter; }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.deps = QtWidgets.QTextEdit(self.tab)
        self.deps.setObjectName("deps")
        self.gridLayout_5.addWidget(self.deps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.makedeps = QtWidgets.QTextEdit(self.tab_2)
        self.makedeps.setObjectName("makedeps")
        self.gridLayout_7.addWidget(self.makedeps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.optdeps = QtWidgets.QTextEdit(self.tab_5)
        self.optdeps.setObjectName("optdeps")
        self.gridLayout_8.addWidget(self.optdeps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_7)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.provides = QtWidgets.QTextEdit(self.tab_3)
        self.provides.setObjectName("provides")
        self.gridLayout_6.addWidget(self.provides, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.conflicts = QtWidgets.QTextEdit(self.tab_4)
        self.conflicts.setObjectName("conflicts")
        self.gridLayout_9.addWidget(self.conflicts, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.replaces = QtWidgets.QTextEdit(self.tab_6)
        self.replaces.setObjectName("replaces")
        self.gridLayout_10.addWidget(self.replaces, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.gridLayout.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.installbrowse = QtWidgets.QPushButton(self.groupBox_4)
        self.installbrowse.setObjectName("installbrowse")
        self.gridLayout_4.addWidget(self.installbrowse, 2, 2, 1, 1)
        self.source_desktop = QtWidgets.QLineEdit(self.groupBox_4)
        self.source_desktop.setObjectName("source_desktop")
        self.gridLayout_4.addWidget(self.source_desktop, 3, 1, 1, 1)
        self.desktopbrowse = QtWidgets.QPushButton(self.groupBox_4)
        self.desktopbrowse.setObjectName("desktopbrowse")
        self.gridLayout_4.addWidget(self.desktopbrowse, 3, 2, 1, 1)
        self.source_install = QtWidgets.QLineEdit(self.groupBox_4)
        self.source_install.setObjectName("source_install")
        self.gridLayout_4.addWidget(self.source_install, 2, 1, 1, 1)
        self.source_package = QtWidgets.QLineEdit(self.groupBox_4)
        self.source_package.setObjectName("source_package")
        self.gridLayout_4.addWidget(self.source_package, 0, 1, 1, 1)
        self.packagetype = QtWidgets.QComboBox(self.groupBox_4)
        self.packagetype.setObjectName("packagetype")
        self.packagetype.addItem("")
        self.packagetype.addItem("")
        self.packagetype.addItem("")
        self.packagetype.addItem("")
        self.packagetype.addItem("")
        self.gridLayout_4.addWidget(self.packagetype, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pkgname = QtWidgets.QLineEdit(self.groupBox)
        self.pkgname.setObjectName("pkgname")
        self.gridLayout_3.addWidget(self.pkgname, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.pkgver = QtWidgets.QLineEdit(self.groupBox)
        self.pkgver.setObjectName("pkgver")
        self.gridLayout_3.addWidget(self.pkgver, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 2, 1, 1)
        self.pkgurl = QtWidgets.QLineEdit(self.groupBox)
        self.pkgurl.setObjectName("pkgurl")
        self.gridLayout_3.addWidget(self.pkgurl, 1, 3, 1, 1)
        self.pkgdesc = QtWidgets.QLineEdit(self.groupBox)
        self.pkgdesc.setObjectName("pkgdesc")
        self.gridLayout_3.addWidget(self.pkgdesc, 2, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.license = QtWidgets.QComboBox(self.groupBox)
        self.license.setObjectName("license")
        self.license.addItem("")
        self.license.setItemText(0, "")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.license.addItem("")
        self.gridLayout_3.addWidget(self.license, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upload = QtWidgets.QPushButton(self.groupBox_6)
        self.upload.setEnabled(False)
        self.upload.setObjectName("upload")
        self.gridLayout_2.addWidget(self.upload, 1, 3, 1, 1)
        self.savesrcbutton = QtWidgets.QPushButton(self.groupBox_6)
        self.savesrcbutton.setObjectName("savesrcbutton")
        self.gridLayout_2.addWidget(self.savesrcbutton, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.startwrite = QtWidgets.QPushButton(self.groupBox_6)
        self.startwrite.setObjectName("startwrite")
        self.gridLayout_2.addWidget(self.startwrite, 1, 0, 1, 1)
        self.savepkgbutton = QtWidgets.QPushButton(self.groupBox_6)
        self.savepkgbutton.setObjectName("savepkgbutton")
        self.gridLayout_2.addWidget(self.savepkgbutton, 1, 1, 1, 1)
        self.maintainer = QtWidgets.QLineEdit(self.groupBox_6)
        self.maintainer.setObjectName("maintainer")
        self.gridLayout_2.addWidget(self.maintainer, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.groupBox_6, 4, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setStyleSheet("font: 8pt \"Monospace\";")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setStyleSheet("font: 10pt \"Monospace\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.gridLayout.addWidget(self.groupBox_3, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quackbuilder"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dependencies"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.deps.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version]  one per line</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", " Depends"))
        self.makedeps.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version]; one per line</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Make Depends"))
        self.optdeps.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version][:reason]; one per line</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Opt. Depends"))
        self.label_6.setText(_translate("MainWindow", "One per line"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Relations"))
        self.provides.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version]</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Provides"))
        self.conflicts.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version]</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Conflicts"))
        self.replaces.setToolTip(_translate("MainWindow", "<html><head/><body><p>pkgname[&gt;=version]</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Replaces"))
        self.label_10.setText(_translate("MainWindow", "One per line"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Source"))
        self.label_7.setText(_translate("MainWindow", "Package"))
        self.label_8.setText(_translate("MainWindow", ".install"))
        self.label_9.setText(_translate("MainWindow", ".desktop"))
        self.installbrowse.setText(_translate("MainWindow", "Browse"))
        self.desktopbrowse.setText(_translate("MainWindow", "Browse"))
        self.source_package.setToolTip(_translate("MainWindow", "<html><head/><body><p>tip</p></body></html>"))
        self.packagetype.setItemText(0, _translate("MainWindow", "Archive"))
        self.packagetype.setItemText(1, _translate("MainWindow", "Git"))
        self.packagetype.setItemText(2, _translate("MainWindow", "Subversion"))
        self.packagetype.setItemText(3, _translate("MainWindow", "Mercurial"))
        self.packagetype.setItemText(4, _translate("MainWindow", "Bazaar"))
        self.groupBox.setTitle(_translate("MainWindow", "Package Info"))
        self.label_2.setText(_translate("MainWindow", "Version:"))
        self.label_3.setText(_translate("MainWindow", "Description:"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "URL:"))
        self.label_5.setText(_translate("MainWindow", "Licence:"))
        self.license.setItemText(1, _translate("MainWindow", "AGPL"))
        self.license.setItemText(2, _translate("MainWindow", "AGPL3"))
        self.license.setItemText(3, _translate("MainWindow", "Apache"))
        self.license.setItemText(4, _translate("MainWindow", "Artistic2.0"))
        self.license.setItemText(5, _translate("MainWindow", "CCPL"))
        self.license.setItemText(6, _translate("MainWindow", "CDDL"))
        self.license.setItemText(7, _translate("MainWindow", "CPL"))
        self.license.setItemText(8, _translate("MainWindow", "EPL"))
        self.license.setItemText(9, _translate("MainWindow", "FDL"))
        self.license.setItemText(10, _translate("MainWindow", "FDL1.2"))
        self.license.setItemText(11, _translate("MainWindow", "FDL1.3"))
        self.license.setItemText(12, _translate("MainWindow", "GPL"))
        self.license.setItemText(13, _translate("MainWindow", "GPL2"))
        self.license.setItemText(14, _translate("MainWindow", "GPL3"))
        self.license.setItemText(15, _translate("MainWindow", "LGPL"))
        self.license.setItemText(16, _translate("MainWindow", "LGPL2.1"))
        self.license.setItemText(17, _translate("MainWindow", "LGPL3"))
        self.license.setItemText(18, _translate("MainWindow", "LPPL"))
        self.license.setItemText(19, _translate("MainWindow", "MPL"))
        self.license.setItemText(20, _translate("MainWindow", "PerlArtistic"))
        self.license.setItemText(21, _translate("MainWindow", "PHP"))
        self.license.setItemText(22, _translate("MainWindow", "PSF"))
        self.license.setItemText(23, _translate("MainWindow", "Ruby"))
        self.license.setItemText(24, _translate("MainWindow", "W3C"))
        self.license.setItemText(25, _translate("MainWindow", "ZPL"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Save && Export"))
        self.upload.setText(_translate("MainWindow", "Upload to AUR4"))
        self.savesrcbutton.setText(_translate("MainWindow", "Save .src.tar.xz"))
        self.label_14.setText(_translate("MainWindow", "Maintained by:"))
        self.startwrite.setText(_translate("MainWindow", "Save PKGBUILD"))
        self.savepkgbutton.setText(_translate("MainWindow", "Save .pkg.tar.xz"))
        self.label_12.setText(_translate("MainWindow", "Made by n3nt0"))
        self.label_13.setText(_translate("MainWindow", "Quackbuilder"))
        self.label_11.setText(_translate("MainWindow", "v0.5.0"))

